<?php

/**
 * This is the model base class for the table "game_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GameDetails".
 *
 * Columns in table "game_details" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $game_id
 * @property integer $userone_id
 * @property integer $usertwo_id
 * @property integer $game_points
 * @property string $game_video_url
 * @property string $game_status
 * @property integer $game_round_one
 * @property integer $game_round_two
 * @property string $game_time
 * @property string $game_word
 * @property string $game_hint
 * @property string $game_category
 *
 */
abstract class BaseGameDetails extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_details';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GameDetails|GameDetails', $n);
	}

	public static function representingColumn() {
		return 'game_video_url';
	}

	public function rules() {
		return array(
			array('userone_id, usertwo_id, game_points, game_video_url, game_status, game_round_one, game_round_two, game_time, game_word, game_hint, game_category', 'required'),
			array('userone_id, usertwo_id, game_points, game_round_one, game_round_two', 'numerical', 'integerOnly'=>true),
			array('game_video_url, game_word, game_hint, game_category', 'length', 'max'=>255),
			array('game_status', 'length', 'max'=>15),
			array('game_id, userone_id, usertwo_id, game_points, game_video_url, game_status, game_round_one, game_round_two, game_time, game_word, game_hint, game_category', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'game_id' => Yii::t('app', 'Game'),
			'userone_id' => Yii::t('app', 'Userone'),
			'usertwo_id' => Yii::t('app', 'Usertwo'),
			'game_points' => Yii::t('app', 'Game Points'),
			'game_video_url' => Yii::t('app', 'Game Video Url'),
			'game_status' => Yii::t('app', 'Game Status'),
			'game_round_one' => Yii::t('app', 'Game Round One'),
			'game_round_two' => Yii::t('app', 'Game Round Two'),
			'game_time' => Yii::t('app', 'Game Time'),
			'game_word' => Yii::t('app', 'Game Word'),
			'game_hint' => Yii::t('app', 'Game Hint'),
			'game_category' => Yii::t('app', 'Game Category'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('game_id', $this->game_id);
		$criteria->compare('userone_id', $this->userone_id);
		$criteria->compare('usertwo_id', $this->usertwo_id);
		$criteria->compare('game_points', $this->game_points);
		$criteria->compare('game_video_url', $this->game_video_url, true);
		$criteria->compare('game_status', $this->game_status, true);
		$criteria->compare('game_round_one', $this->game_round_one);
		$criteria->compare('game_round_two', $this->game_round_two);
		$criteria->compare('game_time', $this->game_time, true);
		$criteria->compare('game_word', $this->game_word, true);
		$criteria->compare('game_hint', $this->game_hint, true);
		$criteria->compare('game_category', $this->game_category, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}