<?php

/**
 * This is the model base class for the table "achievements".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Achievements".
 *
 * Columns in table "achievements" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ach_id
 * @property integer $user_id
 * @property string $game_category
 * @property integer $ach_count
 * @property string $status
 *
 */
abstract class BaseAchievements extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'achievements';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Achievements|Achievements', $n);
	}

	public static function representingColumn() {
		return 'game_category';
	}

	public function rules() {
		return array(
			array('user_id, game_category, ach_count, status', 'required'),
			array('user_id, ach_count', 'numerical', 'integerOnly'=>true),
			array('game_category', 'length', 'max'=>255),
			array('status', 'length', 'max'=>5),
			array('ach_id, user_id, game_category, ach_count, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ach_id' => Yii::t('app', 'Ach'),
			'user_id' => Yii::t('app', 'User'),
			'game_category' => Yii::t('app', 'Game Category'),
			'ach_count' => Yii::t('app', 'Ach Count'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ach_id', $this->ach_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('game_category', $this->game_category, true);
		$criteria->compare('ach_count', $this->ach_count);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}