<?php

/**
 * This is the model base class for the table "user_details".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserDetails".
 *
 * Columns in table "user_details" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property string $user_alternate_id
 * @property string $user_email
 * @property string $user_password
 * @property string $user_name
 * @property string $user_points
 * @property integer $dynamite_number
 * @property string $game_type
 *
 */
abstract class BaseUserDetails extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_details';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserDetails|UserDetails', $n);
	}

	public static function representingColumn() {
		return 'user_alternate_id';
	}

	public function rules() {
		return array(
			array('user_alternate_id, user_email, user_password, user_name, user_points, dynamite_number, game_type', 'required'),
			array('dynamite_number', 'numerical', 'integerOnly'=>true),
			array('user_alternate_id, user_email, user_password, user_name, user_points', 'length', 'max'=>255),
			array('game_type', 'length', 'max'=>4),
			array('user_id, user_alternate_id, user_email, user_password, user_name, user_points, dynamite_number, game_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('app', 'User'),
			'user_alternate_id' => Yii::t('app', 'User Alternate'),
			'user_email' => Yii::t('app', 'User Email'),
			'user_password' => Yii::t('app', 'User Password'),
			'user_name' => Yii::t('app', 'User Name'),
			'user_points' => Yii::t('app', 'User Points'),
			'dynamite_number' => Yii::t('app', 'Dynamite Number'),
			'game_type' => Yii::t('app', 'Game Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('user_alternate_id', $this->user_alternate_id, true);
		$criteria->compare('user_email', $this->user_email, true);
		$criteria->compare('user_password', $this->user_password, true);
		$criteria->compare('user_name', $this->user_name, true);
		$criteria->compare('user_points', $this->user_points, true);
		$criteria->compare('dynamite_number', $this->dynamite_number);
		$criteria->compare('game_type', $this->game_type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}