<?php

/**
 * This is the model base class for the table "game_que".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GameQue".
 *
 * Columns in table "game_que" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $que_id
 * @property integer $user_id
 * @property string $que_status
 * @property string $que_time
 * @property integer $game_count
 *
 */
abstract class BaseGameQue extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'game_que';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GameQue|GameQues', $n);
	}

	public static function representingColumn() {
		return 'que_status';
	}

	public function rules() {
		return array(
			array('user_id, que_status, que_time, game_count', 'required'),
			array('user_id, game_count', 'numerical', 'integerOnly'=>true),
			array('que_status', 'length', 'max'=>4),
			array('que_id, user_id, que_status, que_time, game_count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'que_id' => Yii::t('app', 'Que'),
			'user_id' => Yii::t('app', 'User'),
			'que_status' => Yii::t('app', 'Que Status'),
			'que_time' => Yii::t('app', 'Que Time'),
			'game_count' => Yii::t('app', 'Game Count'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('que_id', $this->que_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('que_status', $this->que_status, true);
		$criteria->compare('que_time', $this->que_time, true);
		$criteria->compare('game_count', $this->game_count);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}